package visao;

public class TelaDeExecucao extends javax.swing.JFrame {

	/**
	 * Creates new form TelaDeExecucao
	 */
	public TelaDeExecucao() {
		initComponents();
	}

	public javax.swing.JLabel getNumeroChamadasCompletadas() {
		return numeroChamadasCompletadas;
	}

	public javax.swing.JLabel getNumeroChamadasNoSistema() {
		return numeroChamadasNoSistema;
	}
        public javax.swing.JLabel getNumeroTempoMedioChamada() {
		return numeroTempoMedioChamada;
	}
	public javax.swing.JLabel getNumeroMaiorTempoChamada() {
		return numeroMaiorTempoChamada;
	}

	public javax.swing.JLabel getNumeroMenorTempoChamada() {
		return numeroMenorTempoChamada;
	}

	public javax.swing.JLabel getNumeroPerdidasC1() {
		return numeroPerdidasC1;
	}

	public javax.swing.JLabel getNumeroPerdidasC2() {
		return numeroPerdidasC2;
	}

	public javax.swing.JButton getBotaoPausarResumir() {
		return botaoPausarResumir;
	}

	public javax.swing.JComboBox getjComboBox1() {
		return jComboBox1;
	}

	public javax.swing.JButton getBotaoEncerrar() {
		return botaoEncerrar;
	}

	public javax.swing.JLabel getTaxaMediaDeOcupacaoDeC1() {
		return taxaMediaDeOcupacaoDeC1;
	}

	public javax.swing.JLabel getTaxaMediaDeOcupacaoDeC2() {
		return taxaMediaDeOcupacaoDeC2;
	}

	public javax.swing.JLabel getNumeroDeCanaisDeC1Ocupados() {
		return numeroDeCanaisDeC1Ocupados;
	}

	public javax.swing.JLabel getNumeroDeCanaisDeC2Ocupados() {
		return numeroDeCanaisDeC2Ocupados;
	}
	
	
	public javax.swing.JLabel getCampoTempoDoEventoFuturo1() {
		return campoTempoDoEventoFuturo1;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo10() {
		return campoTempoDoEventoFuturo10;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo11() {
		return campoTempoDoEventoFuturo11;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo12() {
		return campoTempoDoEventoFuturo12;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo13() {
		return campoTempoDoEventoFuturo13;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo2() {
		return campoTempoDoEventoFuturo2;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo3() {
		return campoTempoDoEventoFuturo3;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo4() {
		return campoTempoDoEventoFuturo4;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo5() {
		return campoTempoDoEventoFuturo5;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo6() {
		return campoTempoDoEventoFuturo6;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo7() {
		return campoTempoDoEventoFuturo7;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo8() {
		return campoTempoDoEventoFuturo8;
	}

	public javax.swing.JLabel getCampoTempoDoEventoFuturo9() {
		return campoTempoDoEventoFuturo9;
	}

	public javax.swing.JLabel getCampoTipoDoEvento1() {
		return campoTipoDoEvento1;
	}

	public javax.swing.JLabel getCampoTipoDoEvento10() {
		return campoTipoDoEvento10;
	}

	public javax.swing.JLabel getCampoTipoDoEvento11() {
		return campoTipoDoEvento11;
	}

	public javax.swing.JLabel getCampoTipoDoEvento12() {
		return campoTipoDoEvento12;
	}

	public javax.swing.JLabel getCampoTipoDoEvento13() {
		return campoTipoDoEvento13;
	}

	public javax.swing.JLabel getCampoTipoDoEvento2() {
		return campoTipoDoEvento2;
	}

	public javax.swing.JLabel getCampoTipoDoEvento3() {
		return campoTipoDoEvento3;
	}

	public javax.swing.JLabel getCampoTipoDoEvento4() {
		return campoTipoDoEvento4;
	}

	public javax.swing.JLabel getCampoTipoDoEvento5() {
		return campoTipoDoEvento5;
	}

	public javax.swing.JLabel getCampoTipoDoEvento6() {
		return campoTipoDoEvento6;
	}

	public javax.swing.JLabel getCampoTipoDoEvento7() {
		return campoTipoDoEvento7;
	}

	public javax.swing.JLabel getCampoTipoDoEvento8() {
		return campoTipoDoEvento8;
	}

	public javax.swing.JLabel getCampoTipoDoEvento9() {
		return campoTipoDoEvento9;
	}

	public javax.swing.JLabel getCampoTempoAtual() {
		return campoTempoAtual;
	}
        
        public javax.swing.JLabel getNumeroMaiorChamadasNoSistema() {
            return numeroMaiorChamadasNoSistema;
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        panelEstatisticas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroChamadasNoSistema = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroChamadasCompletadas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroMenorTempoChamada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numeroTempoMedioChamada = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numeroMaiorTempoChamada = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroPerdidasC1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numeroPerdidasC2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numeroDeCanaisDeC1Ocupados = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        taxaMediaDeOcupacaoDeC1 = new javax.swing.JLabel();
        numeroDeCanaisDeC2Ocupados = new javax.swing.JLabel();
        taxaMediaDeOcupacaoDeC2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numeroMaiorChamadasNoSistema = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        botaoPausarResumir = new javax.swing.JButton();
        botaoEncerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoTempoAtual = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo1 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo2 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo4 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo3 = new javax.swing.JLabel();
        campoTipoDoEvento1 = new javax.swing.JLabel();
        campoTipoDoEvento2 = new javax.swing.JLabel();
        campoTipoDoEvento3 = new javax.swing.JLabel();
        campoTipoDoEvento4 = new javax.swing.JLabel();
        campoTipoDoEvento5 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo5 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo6 = new javax.swing.JLabel();
        campoTipoDoEvento6 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo7 = new javax.swing.JLabel();
        campoTipoDoEvento7 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo8 = new javax.swing.JLabel();
        campoTipoDoEvento8 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo9 = new javax.swing.JLabel();
        campoTipoDoEvento9 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo10 = new javax.swing.JLabel();
        campoTipoDoEvento10 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo11 = new javax.swing.JLabel();
        campoTipoDoEvento11 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo12 = new javax.swing.JLabel();
        campoTipoDoEvento12 = new javax.swing.JLabel();
        campoTempoDoEventoFuturo13 = new javax.swing.JLabel();
        campoTipoDoEvento13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Execucao");

        panelEstatisticas.setBorder(javax.swing.BorderFactory.createTitledBorder("Estatisticas"));
        panelEstatisticas.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(numeroChamadasNoSistema);
        jLabel1.setText("Entidades no sistema");

        numeroChamadasNoSistema.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tempo medio no sistema entidade 2");

        numeroChamadasCompletadas.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Trocas da entidade 2");

        numeroMenorTempoChamada.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tempo medio na fila entidade 2");

        numeroTempoMedioChamada.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Quantidade de entidades já saíram");

        numeroMaiorTempoChamada.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Quantidade de falhas servidor 1");

        numeroPerdidasC1.setText("0");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Quantidade de falhas servidor 2");

        numeroPerdidasC2.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tempo médio na fila entidade 1");

        numeroDeCanaisDeC1Ocupados.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Tempo em falha servidor 1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tempo medio no sistema entidade 1");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Tempo em falha servidor 2");

        taxaMediaDeOcupacaoDeC1.setText("0");

        numeroDeCanaisDeC2Ocupados.setText("0");

        taxaMediaDeOcupacaoDeC2.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Trocas da entidade 1");

        numeroMaiorChamadasNoSistema.setText("0");

        javax.swing.GroupLayout panelEstatisticasLayout = new javax.swing.GroupLayout(panelEstatisticas);
        panelEstatisticas.setLayout(panelEstatisticasLayout);
        panelEstatisticasLayout.setHorizontalGroup(
            panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatisticasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEstatisticasLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEstatisticasLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(58, 58, 58)))
                    .addGroup(panelEstatisticasLayout.createSequentialGroup()
                        .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addGroup(panelEstatisticasLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(numeroDeCanaisDeC1Ocupados, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(taxaMediaDeOcupacaoDeC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroDeCanaisDeC2Ocupados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taxaMediaDeOcupacaoDeC2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroMaiorTempoChamada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroMenorTempoChamada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroTempoMedioChamada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroChamadasCompletadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroPerdidasC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroPerdidasC2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroMaiorChamadasNoSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroChamadasNoSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEstatisticasLayout.setVerticalGroup(
            panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroChamadasNoSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numeroMaiorChamadasNoSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numeroDeCanaisDeC1Ocupados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(taxaMediaDeOcupacaoDeC1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroDeCanaisDeC2Ocupados)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxaMediaDeOcupacaoDeC2)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroMaiorTempoChamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroMenorTempoChamada)
                    .addComponent(jLabel5))
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstatisticasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(numeroChamadasCompletadas))
                    .addGroup(panelEstatisticasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(numeroTempoMedioChamada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroPerdidasC1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstatisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPerdidasC2)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Passo", "3 Passos", "5 Passos" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        botaoPausarResumir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoPausarResumir.setText("Pausar");
        botaoPausarResumir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPausarResumirActionPerformed(evt);
            }
        });

        botaoEncerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoEncerrar.setText("Encerrar");
        botaoEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoPausarResumir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoEncerrar)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPausarResumir)
                    .addComponent(botaoEncerrar))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tempo:");

        campoTempoAtual.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        campoTempoAtual.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eventos Futuros"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tempo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo do  Evento");

        campoTempoDoEventoFuturo1.setText("jLabel18");

        campoTempoDoEventoFuturo2.setText("jLabel18");

        campoTempoDoEventoFuturo4.setText("jLabel18");

        campoTempoDoEventoFuturo3.setText("jLabel18");

        campoTipoDoEvento1.setText("jLabel18");

        campoTipoDoEvento2.setText("jLabel18");

        campoTipoDoEvento3.setText("jLabel18");

        campoTipoDoEvento4.setText("jLabel18");

        campoTipoDoEvento5.setText("jLabel18");

        campoTempoDoEventoFuturo5.setText("jLabel18");

        campoTempoDoEventoFuturo6.setText("jLabel18");

        campoTipoDoEvento6.setText("jLabel18");

        campoTempoDoEventoFuturo7.setText("jLabel18");

        campoTipoDoEvento7.setText("jLabel18");

        campoTempoDoEventoFuturo8.setText("jLabel18");

        campoTipoDoEvento8.setText("jLabel18");

        campoTempoDoEventoFuturo9.setText("jLabel18");

        campoTipoDoEvento9.setText("jLabel18");

        campoTempoDoEventoFuturo10.setText("jLabel18");

        campoTipoDoEvento10.setText("jLabel18");

        campoTempoDoEventoFuturo11.setText("jLabel18");

        campoTipoDoEvento11.setText("jLabel18");

        campoTempoDoEventoFuturo12.setText("jLabel18");

        campoTipoDoEvento12.setText("jLabel18");

        campoTempoDoEventoFuturo13.setText("jLabel18");

        campoTipoDoEvento13.setText("jLabel18");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoTempoDoEventoFuturo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipoDoEvento6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTempoDoEventoFuturo1)
                                    .addComponent(campoTempoDoEventoFuturo2)
                                    .addComponent(campoTempoDoEventoFuturo3)
                                    .addComponent(campoTempoDoEventoFuturo4)
                                    .addComponent(campoTempoDoEventoFuturo5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTipoDoEvento2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoTipoDoEvento1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoTipoDoEvento3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoTipoDoEvento4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoTipoDoEvento5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTempoDoEventoFuturo1)
                    .addComponent(campoTipoDoEvento1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTempoDoEventoFuturo2)
                    .addComponent(campoTipoDoEvento2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTempoDoEventoFuturo3)
                    .addComponent(campoTipoDoEvento3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTempoDoEventoFuturo4)
                    .addComponent(campoTipoDoEvento4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTempoDoEventoFuturo5)
                    .addComponent(campoTipoDoEvento5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTipoDoEvento6)
                    .addComponent(campoTempoDoEventoFuturo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento7)
                    .addComponent(campoTempoDoEventoFuturo7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento8)
                    .addComponent(campoTempoDoEventoFuturo8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento9)
                    .addComponent(campoTempoDoEventoFuturo9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento10)
                    .addComponent(campoTempoDoEventoFuturo10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento11)
                    .addComponent(campoTempoDoEventoFuturo11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento12)
                    .addComponent(campoTempoDoEventoFuturo12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoDoEvento13)
                    .addComponent(campoTempoDoEventoFuturo13))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Velocidade de Execucao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(campoTempoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoTempoAtual))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBox1ItemStateChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox1ItemStateChanged

	private void botaoEncerrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEncerrarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_botaoEncerrarActionPerformed

	private void botaoPausarResumirActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoPausarResumirActionPerformed
		// TODO add your handling code here:
		if (botaoPausarResumir.getText().equals("Pausar")) {
			botaoPausarResumir.setText("Resumir");
		} else if (botaoPausarResumir.getText().equals("Resumir")) {
			botaoPausarResumir.setText("Pausar");
		}
	}// GEN-LAST:event_botaoPausarResumirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEncerrar;
    private javax.swing.JButton botaoPausarResumir;
    private javax.swing.JLabel campoTempoAtual;
    private javax.swing.JLabel campoTempoDoEventoFuturo1;
    private javax.swing.JLabel campoTempoDoEventoFuturo10;
    private javax.swing.JLabel campoTempoDoEventoFuturo11;
    private javax.swing.JLabel campoTempoDoEventoFuturo12;
    private javax.swing.JLabel campoTempoDoEventoFuturo13;
    private javax.swing.JLabel campoTempoDoEventoFuturo2;
    private javax.swing.JLabel campoTempoDoEventoFuturo3;
    private javax.swing.JLabel campoTempoDoEventoFuturo4;
    private javax.swing.JLabel campoTempoDoEventoFuturo5;
    private javax.swing.JLabel campoTempoDoEventoFuturo6;
    private javax.swing.JLabel campoTempoDoEventoFuturo7;
    private javax.swing.JLabel campoTempoDoEventoFuturo8;
    private javax.swing.JLabel campoTempoDoEventoFuturo9;
    private javax.swing.JLabel campoTipoDoEvento1;
    private javax.swing.JLabel campoTipoDoEvento10;
    private javax.swing.JLabel campoTipoDoEvento11;
    private javax.swing.JLabel campoTipoDoEvento12;
    private javax.swing.JLabel campoTipoDoEvento13;
    private javax.swing.JLabel campoTipoDoEvento2;
    private javax.swing.JLabel campoTipoDoEvento3;
    private javax.swing.JLabel campoTipoDoEvento4;
    private javax.swing.JLabel campoTipoDoEvento5;
    private javax.swing.JLabel campoTipoDoEvento6;
    private javax.swing.JLabel campoTipoDoEvento7;
    private javax.swing.JLabel campoTipoDoEvento8;
    private javax.swing.JLabel campoTipoDoEvento9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numeroChamadasCompletadas;
    private javax.swing.JLabel numeroChamadasNoSistema;
    private javax.swing.JLabel numeroDeCanaisDeC1Ocupados;
    private javax.swing.JLabel numeroDeCanaisDeC2Ocupados;
    private javax.swing.JLabel numeroMaiorChamadasNoSistema;
    private javax.swing.JLabel numeroMaiorTempoChamada;
    private javax.swing.JLabel numeroMenorTempoChamada;
    private javax.swing.JLabel numeroPerdidasC1;
    private javax.swing.JLabel numeroPerdidasC2;
    private javax.swing.JLabel numeroTempoMedioChamada;
    private javax.swing.JPanel panelEstatisticas;
    private javax.swing.JLabel taxaMediaDeOcupacaoDeC1;
    private javax.swing.JLabel taxaMediaDeOcupacaoDeC2;
    // End of variables declaration//GEN-END:variables
}
